name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Debug environment
        run: |
          echo "=== Node.js version ==="
          node --version
          npm --version
          echo "=== PostCSS CLI version ==="
          npx postcss --version
          echo "=== Project structure ==="
          find src/css -name "*.css" -type f
          echo "=== PostCSS config ==="
          cat postcss.config.js

      - name: Run lint
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Build project
        run: |
          echo "Running build:tokens..."
          npm run build:tokens || exit 1
          
          echo "Running build:css..."
          npm run build:css || {
            echo "PostCSS failed, trying fallback..."
            npm run build:css:fallback || exit 1
          }
          
          echo "Running build:js..."
          npm run build:js || exit 1

      - name: Verify build output
        run: |
          echo "=== Build output ==="
          ls -la css/ || echo "css/ directory not found"
          ls -la dist/ || echo "dist/ directory not found"
