name: Publish to NPM

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Debug environment
        run: |
          echo "=== Node.js version ==="
          node --version
          npm --version
          echo "=== PostCSS CLI version ==="
          npx postcss --version
          echo "=== Project structure ==="
          find src/css -name "*.css" -type f
          echo "=== PostCSS config ==="
          cat postcss.config.js

      - name: Build project
        run: |
          echo "Running build:tokens..."
          npm run build:tokens || exit 1

          echo "Running build:css..."
          npm run build:css || {
            echo "PostCSS failed, trying fallback..."
            npm run build:css:fallback || exit 1
          }

          echo "Running build:js..."
          npm run build:js || exit 1

      - name: Verify build output
        run: |
          echo "=== Build output ==="
          ls -la css/
          ls -la dist/

      - run: npm publish --provenance --access public

      - name: Check NPM authentication
        run: |
          echo "Checking NPM authentication..."
          echo "Registry: $(npm config get registry)"
          echo "Auth token present: $([[ -n "$NODE_AUTH_TOKEN" ]] && echo "YES" || echo "NO")"
          npm whoami || echo "NPM authentication failed"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Test publish (dry run)
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
