name: Publish to NPM

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify NPM authentication
        run: |
          echo "=== Debug NPM Configuration ==="
          echo "NODE_AUTH_TOKEN present: $([[ -n "$NODE_AUTH_TOKEN" ]] && echo "YES" || echo "NO")"
          echo "NPM_CONFIG_USERCONFIG: $NPM_CONFIG_USERCONFIG"
          echo "Default registry: $(npm config get registry)"
          echo "Auth config: $(npm config get //registry.npmjs.org/:_authToken)"
          echo ""
          echo "=== Attempting whoami ==="
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
